# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4243007fc8cfa7614f8454eed07cd87cf2fd8eac178478c7b5a5a761bdf21b9fe57e7648484808af1f9586a362ee97874bbc54616366cc930867cfebbfb4ce0b

test:
  secret_key_base: 9b13adf97cd60e233c10b8fcdba24b20d568ee25b31d53b6dd15ebd90d10059513b7f0bbca9896fb622697b0e4386a0115010844b7e58adccdb411a5c2de3251

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
